theme: jekyll-theme-architect
title: Mental Scaffolding for Product Marketing, Product Management and Technology Management
description: This page has mental models, frameworks useful for product management, marketing, and entrepreneurs.
